#!/bin/bash

# shellcheck disable=SC2034
CURRENT_DIR=$(pwd)
SOURCE_DIR=$(readlink -f "$SOURCE_DIR")
DOCS_DIR="$SOURCE_DIR/$DOCS_NAME"
ENV=${ENV:-prod}
GIT_SSH_URL=${GIT_SSH_URL:-git@github.com:cslant}
DOCS_REPO="$GIT_SSH_URL/$DOCS_REPO.git"
USE_SUBMODULES=${USE_SUBMODULES:-false}
SSH_NAME=${SSH_NAME:-cslant}
SSH_DOCS_PATH=${SSH_DOCS_PATH:-/home/cslant/docs.cslant.com}
SSH_RELEASES_DIR=${SSH_RELEASES_DIR:-${SSH_DOCS_PATH}-releases}
SSH_LIVE_NAME=${SSH_LIVE_NAME:-current}
SSH_DOCS_LIVE="$SSH_DOCS_PATH/$SSH_LIVE_NAME"
KEEP_RELEASES=${KEEP_RELEASES:-5}
DOCS_PUBLIC_URL=${DOCS_PUBLIC_URL:-https://docs.cslant.com}
PREWARM_MAX=${PREWARM_MAX:-80}
